# Update all the sections by editing the data.yml file inside _data folder.

# Site Settings

# SEO plugin
title: Resume Esteban Casas
author: Esteban Alberto Casas Nieto
tagline: Senior Software Developer | Ex-Google # Short description for jekyll-seo-tag
description: Resume Esteban Casas | Senior Software Developer | Ex-Google # Longer description for jekyll-seo-tag

url: "https://ecasasni.github.io"
baseurl: "/resume" # change it according to your repository name

twitter:
  username: _ecasasni
  card: summary

social:
  links:
    # - https://twitter.com/stevedoe123
    # - https://www.facebook.com/stevedoe123
    - https://www.linkedin.com/in/ecasasni
    - https://github.com/ecasasni
    # - https://keybase.io/stevedoe123

google_site_verification: # Put your google verification tag here

# End SEO

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # gray blue turquoise green berry red

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
